/var/spool/slurm/job35902135/slurm_script: line 17: /ibex/user/alvarem/miniconda3/bin/activate: No such file or directory
/home/alvarem/bridge/bridge.py:1967: RuntimeWarning: invalid value encountered in divide
  w5_den=(w1-wmin)/np.sum((w1-wmin))
/home/alvarem/bridge/bridge.py:2092: RuntimeWarning: invalid value encountered in divide
  w5_den=(w1-wmin)/np.sum((w1-wmin))
/home/alvarem/bridge/bridge.py:1967: RuntimeWarning: invalid value encountered in divide
  w5_den=(w1-wmin)/np.sum((w1-wmin))
/home/alvarem/bridge/bridge.py:2092: RuntimeWarning: invalid value encountered in divide
  w5_den=(w1-wmin)/np.sum((w1-wmin))
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/alvarem/miniconda3/envs/loc/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/alvarem/miniconda3/envs/loc/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/alvarem/bridge/Par_loc.py", line 464, in Prl_C_SGD_ou_bridge
    bdg.C_Grad_Cond_PF_bridge_back_samp(cond_path_0,cond_path_1,seeds_cond_0,seeds_cond_1,t0,x0,T,b,\
  File "/home/alvarem/bridge/bridge.py", line 5174, in C_Grad_Cond_PF_bridge_back_samp
    =C_Cond_PF_bridge_back_samp(x_cond_0,x_cond_1,\
  File "/home/alvarem/bridge/bridge.py", line 4660, in C_Cond_PF_bridge_back_samp
    [j_0,j_1, ir_v_0,ir_v_1]=max_coup_multi_sing_samp(degen_weights_0,degen_weights_1,ir_v_0,ir_v_1,1)
  File "/home/alvarem/bridge/bridge.py", line 2094, in max_coup_multi_sing_samp
    [part1[bino:],x1_new[bino:]]=multi_samp(w5_den,N-bino,x1,dim)
  File "/home/alvarem/bridge/bridge.py", line 1926, in multi_samp
    part_samp=np.random.choice(len(W),size=N,p=W,replace=True) #particles resampled
  File "mtrand.pyx", line 954, in numpy.random.mtrand.RandomState.choice
ValueError: probabilities contain NaN
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/alvarem/bridge/Par_loc.py", line 614, in <module>
    pool_outputs = pool.map(Prl_C_SGD_ou_bridge,inputs)
  File "/home/alvarem/miniconda3/envs/loc/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/alvarem/miniconda3/envs/loc/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
ValueError: probabilities contain NaN
