/var/spool/slurm/job35971798/slurm_script: line 17: /ibex/user/alvarem/miniconda3/bin/activate: No such file or directory
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/alvarem/miniconda3/envs/loc/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/alvarem/miniconda3/envs/loc/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/alvarem/bridge/Par_loc.py", line 530, in fibonacci
    for _ in range(n):
TypeError: 'numpy.float64' object cannot be interpreted as an integer
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/alvarem/bridge/Par_loc.py", line 565, in <module>
    pool_outputs = pool.map(fibonacci,inputs)
  File "/home/alvarem/miniconda3/envs/loc/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/alvarem/miniconda3/envs/loc/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
TypeError: 'numpy.float64' object cannot be interpreted as an integer
